default_platform(:ios)

platform :ios do
# 1
  desc "Create app on Apple Developer and App Store Connect sites"
  lane :create_app do
   produce
  end
# 2
  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end
# 3  
	desc "Create ipa"
  lane :build do
    # 1
    enable_automatic_code_signing
    # 2
    increment_build_number
    # 3
    gym
  end
# 4
  desc "Upload to App Store"
  lane :upload do
    deliver
  end
end
