default_platform(:ios)

platform :ios do
	desc "Create ipa"
  lane :build do
    enable_automatic_code_signing
    increment_build_number
    gym
  end
  desc "Upload to App Store"
  lane :upload do
    deliver
  end
  desc “Create app, take screenshots, build and upload to App Store"
  lane :do_everything do
    build
    upload
  end
end
